// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnnouncement():Promise<string>;

export function Open(arg1:string):Promise<void>;

export function ProxyList():Promise<Array<string>>;

export function Switch(arg1:boolean,arg2:string,arg3:boolean):Promise<string>;

export function Version():Promise<string>;

export interface ProxyInfo {
    name: string;
    protocol: string;
    method?: string;
    password?: string;
    host: string;
    port: number;
}

export function LoadSubscription(arg1:string):Promise<ProxyInfo[]>;

export function LoadLocalFile(arg1:string):Promise<ProxyInfo[]>;

export function GetAccountStatus():Promise<string>;
