// @ts-check
// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnnouncement() {
  return window['go']['main']['App']['GetAnnouncement']();
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function ProxyList() {
  return window['go']['main']['App']['ProxyList']();
}

export function Switch(arg1, arg2, arg3) {
  return window['go']['main']['App']['Switch'](arg1, arg2, arg3);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function LoadSubscription(arg1) {
  return window['go']['main']['App']['LoadSubscription'](arg1);
}

export function LoadLocalFile(arg1) {
  return window['go']['main']['App']['LoadLocalFile'](arg1);
}

export function GetAccountStatus() {
  return window['go']['main']['App']['GetAccountStatus']();
}
